config/routes.rb
Kuchen::Application.routes.draw do

  resources :cakes do
    post 'bid'
    resources :cake_photos do

    end
  end

  root :to => "cakes#index"

end

app/models/cake.rb
class Cake < ActiveRecord::Base
    has_many :cake_photos, :inverse_of =>  :cake

end

app/models/cake_photo.rb
class CakePhoto < ActiveRecord::Base
   belongs_to :cake
   has_attached_file :photo,
    :styles => {
      :thumb=> "100x100#",
      :small  => "150x150>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cake_photos_controller.rb
class CakePhotosController < ApplicationController
  def create
    puts "#####{params.inspect}"
    @cake = Cake.find_by_id params[:cake_id]
    @cake.cake_photos.create(params[:cake_photo])

    redirect_to edit_cake_path(:id=>@cake.id)

  end
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
  def index
    @cakes=Cake.all
    @special = Cake.first
  end

  def new
    @cake = Cake.new

  end
  def update
    @cake = Cake.find_by_id params[:id]
    if @cake.nil?
      redirect_to :back
    else
      @cake.update_attributes params[:cake]
      @cake.save
      redirect_to :action=>:edit, :id=>@cake.id
    end
  end

  def create
    @cake = Cake.new params[:cake]
    @cake.save
    redirect_to :action=>:new
  end
  def edit
    puts params.inspect
    @cake = Cake.find_by_id params[:id]
    render 'new'
  end
  def destroy
    @cake = Cake.find_by_id params[:id]
    @cake.delete
    redirect_to :action=>:index
  end

  def upload_photo
    @cake = Cake.find_by_id params[:id]
    @photo = params[:cake]
  end
end

app/helpers/application_helper.rb
require 'labelling_form_builder'
module ApplicationHelper

  def labelled_form_for(object, options, &proc)
    form_for(object, options.merge(:builder => LabellingFormBuilder), &proc)
  end

  def multipart_form_for(object, options, &proc)
    html_options = options.delete(:html) || {}
    html_options.merge!(:multipart => true)
    form_for(object, options.merge(:html => html_options), &proc)
  end

  def labelled_multipart_form_for(object, options, &proc)
    multipart_form_for(object, options.merge(:builder => LabellingFormBuilder), &proc)
  end


end

app/helpers/cakes_helper.rb
module CakesHelper
end

app/views/cakes/index.html.haml
#content

  %section.cake.special
    %h1
      Today We're baking...
    %div.name
      %h3
        = @special.name
    %div.description
      = @special.description
      = button_to 'Bid', cakes_path( :id => @special.id ), :method => :bid
      = button_to 'Delete', cakes_path( :id => @special.id ), :method => :delete
    %div.photos
      = image_tag @special.cake_photos.first.photo.url(:thumb)
  %section.cake.older

app/views/cakes/new.html.haml
-action = @cake.id ? :create : :update

-labelled_form_for @cake, {} do |f|
  =raw f.text_field :name
  =raw f.text_field :description
  =raw f.submit

-if @cake.id
  -labelled_multipart_form_for [@cake,CakePhoto.new], {:cake_id=>@cake.id} do |f|
    =raw f.file_field :photo
    =raw f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Kuchen</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
</head>
<body>
<div id='outer_content'>
    <div id="header">
        <nav>
            <div><a href="#">
                <img id='about' src='/images/sekt.jpg'/>
                About us
            </a>
            </div>
            <div>
                <a href="#">
                    <img id='like' src='/images/apfel.jpg'/>
                    Like
                </a>
            </div>
            <div>
                <a href="#">
                    <img id='contact' src='/images/apfel2.jpg'/>
                    Contact
                </a>

            </div>

            <!--<img src='/images/germany.png'/><img src='/images/usa.png'/>-->
    </div>

    <%= yield %>

</div>
</body>
</html>